sudo: required
language: node_js
node_js:
- '8'
services:
- docker
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_eee3a2e3a3e3_key -iv $encrypted_eee3a2e3a3e3_iv
  -in google-cloud-key.json.enc -out google-cloud-key.json -d
install: npm install
stages:
- lint
- test
- coverage
- deploy
jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: test
    script: npm test
  - stage: coverage
    script:
    - npm run coverage
    - npm run coveralls
  - stage: deploy
    script:
    - docker login --username=_ --password=$HEROKU_TOKEN
    - docker build -t registry.heroku.com/shared-server-stories/web .
    - docker push registry.heroku.com/shared-server-stories/web
    on:
      branch: docker_to_heroku
      repo: taller2-2018-1-grupo2/shared-server
