language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_eee3a2e3a3e3_key -iv $encrypted_eee3a2e3a3e3_iv
  -in google-cloud-key.json.enc -out google-cloud-key.json -d
install: npm install
stages:
- lint
- test
- coverage
- deploy_staging
- deploy_production
jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: test
    script: npm test
  - stage: coverage
    script:
    - npm run coverage
    - npm run coveralls
  - stage: deploy_staging
    script: ignore
    deploy:
    - provider: heroku
      app: shared-server-stories-staging
      skip_cleanup: true
      api_key:
        secure: dY0BtBaLxOsBdGVdQLXIakfS6a/h4Na53wkB/6LbF/VJolhy+A8vK0SFw32lQ19K49Xz8Dj3PHULOMbQMDk6ExSEG0m4kkVscUXRjNcC8skyH8DdpZV4zN1KwdUupWvUULSI1Jw5pJr6HcBqV1CYfKa6ZANhbBqjKdldcwHqZNWk3bCe18qubC09Ljrpd6wvck2gczjXG9rjWlFWCYr7LpnjSHWbDZacs0xHwTdc7GukiewkpeGTcWb196u/BHXe5NwO1EiR5nmenddpy1FQf8X7O/MxrkRa5I61dMbiK4YpeeEnVtQZf8fgkynbaGfYpzHQIgoR4YTmRp6rSXNlyQ0htNpOpwOWgUaVXv9lfDzBEJxY+EH1307+WzQPzwob7arud9A68fpHETM5vdBxQQDkF234ExFnXfGhSsdkeiurM0cKLoJIkvj390CbzTmFyO1qChWbSdMTj6NGiP5r54yxMCWba7XKf2QezY3x9cs/bzmL2wjqJaYjrbm+2n0SI5GaBd1In7jx9pQxLVc74iDD17Oi0qexqEaCob0UVvdAovVNtf8FAaq7q1Kqn0gDYg52Fl840dC+D9IYGlxRN8mcx8g7q1dEV5q0CsWLajVKuzNHxx7xBL/FqqJte0KMuWtrn88ddXKsS3XE0tj9hkAhpJlvjpgsoJhrXetVSMI=
      on:
        branch: master
        repo: taller2-2018-1-grupo2/shared-server
  - stage: deploy_production
    script: ignore
    deploy:
    - provider: heroku
      app: shared-server-stories
      skip_cleanup: true
      api_key:
        secure: cBvXGnrwoOtZkvikhtbq4Y08w53IpbsaszkpLNnkX8Y+rH9DES+DEXYAoILiUfGjAOoVCJA0aFnsYLThzUJSuZbgs9vIsQF0cOQFu6ACa+lNiKeptBXzP2wupTqa2iai2SKI9+R3H6CnIr+zCJ2LSfTM4vP1rvuA7TyhmcWaKtrx4957yRqM5mv0VF3w7BErgpBGA25nwXhHAbOQv/AJWDSyn9PCl2LmzSCWoepzhFhni3ivu2o55/0BNyPoTSeIehOd/J3Dm5vbjw0smWHDXRob9eLkbC4+AlqAawahTqgqXP3LbhbvV3xEDknDaq5x48V+cekbeXOSesweJOwcJTSiPXoFqvb7OasH6ioIf4+k7n0vGyPoBfPVY/ebJ2e9u/I/Z0iR5fL9lJAIqRrr+XzyapJZwEJXICrrMkgrBL7QvxsOmXq9yYhldCeu8mcGVGNh6jC4XdGmackYOGRJ/83pUDhv4AKnhXANovPvuZyShtkkkF8joffhT8uL8kcVlve/8GkzjKLDY9cq95pEUs+ijniL8oZXQXzALJSMYYVkjKFPQrLC7y2vqWEYxxOJ2/DA2StTte53/6JXZNPC665Cf82fUxDU8VDd7/ygKZ4FNkEJtg/Jhb2TAS0Xs9spKzwu14/ivTIMafHvCarzNTFWB4DtXBjHdvlQ5kBO63c=
      on:
        branch: master
        repo: taller2-2018-1-grupo2/shared-server
