language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install: npm install
stages:
- lint
- test
- coverage
- deploy
jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: test
    script: npm test
  - stage: coverage
    script: npm run coverage_dev
  - stage: deploy_heroku_mariano
    script: ignore
    deploy:
      on:
        branch: master
      provider: heroku
      app: stories-shared-server
      api_key:
        secure: Hp6NZi5ovFnRvLBwbmZjRHV96xPf3EVboQlMK3hRt8X5oYuJDxhB3lyQmEbkbXl7DN2bN7RV7yyo/79cgXokov+LPtTCIce62+lKCspkgMbkNPNJhoEKbh4FARHMJYaccOuUjYCSVDvE3xcEBDHPwNgREaJrlmw8OotaJhP8p8xDHgZOCy4oIUJAql+Mjn06rRWBwinzZnK9/ORzOzT0HHL1HNG7564zrupkZFrSaVpOPJujorQR7JbvHVF+zX1CQLwcHIVsgAHGZTaJGhHUhypavO0MHqdswfFFoXDvktR+Co6IGS5ih17rAdzYzWub33xQ2f+UAms5uhan2lMEIHeXffIXHuItvAqImfKha9y5GVhmh4TLHN87/mXgDeaiVsZnyLiNaY+0qa9/zYZYSU4w9NKdnCoTLKDqtYSYUn4Fol33pQTGI+ef48KzqiYD3gIVLd+sMegyfLF0IPfYJJG1PxmdEWvJA7f/WNWK5OiU+ZB+agbYwMmh5wDi0FRpxGR4YIKb0rSr+dZXC4mJOw1omg4j4MSYAa4XRaats0LMKRrOJsrPUq8k6tDHv3pxxEGYG/vgb4SRl5Kd+Tb5UP2wC7eHuPAzHyYQ27g/mdJf5blfccDivO2BJXsNuEmmLGAkGx4wHt0qdmfuXElMn+Z6TZ9AFShkow1KFxaIQxg=
  - stage: deploy_heroku_gonza
    script: ignore
    deploy:
      on:
        branch: master
      provider: heroku
      app: shared-server
      api_key:
        secure: SgQAk6JvA8KyfXhgjM3BMJZDGW0HvVksD870cY/GtaR1anlzyAOCvG9NPvU8oRcUXzWw4/+CXAXuz6Xt/Dl4ntzGzja7fHBPwVjm4h8okqybIGGrWnEiO0eLD27F9ufpT7RXk49ndYGCyQi8f4pPHYYPD2f8xXzQTrvsaBJe1vj78kvGMavSoCsXt0DiA2mGlV30YqIw/LGAJbrWNykDtjkOW/xJppDdis7JDGIoLsJQuUqInxIimjg36JzuilKOSCWZTV+2Rvt8bDacTOzCqQ73tAhdOwbg7veMihj0t2m2LND3Iw0/6S3Zq7oQRGWR4z4FU4gJ0iW5D4F18fwNtDCIrBAo9hw56ZQi/Ynmjn9d9iDBKyZHJn/FjI6sg4OszKtrOhXNxes+DV0jehBasP+q/CYwmihK5xC2SsdKvG27KT1onKanWcThpDLKpiPdu66sKz74TSG30jnPQBWukIVlE0DXv4m9TsCkVxBissXp5S18UHh3GxWoQoHhhQeUVL4Px4vOJnUjgHNHlOjBFati7ElyhlH7aAz/SaRgEPVfRviEIbKYkAEIto/YFdfIu29qfUBHj4No5gTM8vD0ApLWAk1Camu0nUQbO+rV1sFI4VEAQ9p1uzLFwkWQuySli8YNA+F1iVtegeRXbEu1K7bjI5S3z1ibgB/8v+KC7oA=
      on:
        repo: taller2-2018-1-grupo2/shared-server
